name: Example

# TODO: reset this
on: push
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#   push:
#     branches:
#       - main

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      runs-on: ubuntu-latest

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    with:
      runs-on: ubuntu-latest
  # test:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v3
  #     - name: Set up Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16

  #     - name: Install dependencies
  #       run: yarn

  #     - name: Static analysis
  #       run: |
  #         yarn typecheck
  #         yarn eslint
  #         yarn prettier

  #     - name: Unit tests
  #       run: yarn test:unit

  #     - name: Install op CLI
  #       uses: simonbs/install-op-cli@1.0.0
  #       with:
  #         version-number: 2.15.0-beta.03

  #     - name: Verify op installation
  #       run: echo "Installed \`op\` version $(op --version)"

  #     - name: Configure 1Password Service Account
  #       uses: 1password/load-secrets-action/configure@v1
  #       with:
  #         service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  #     - name: Integration tests
  #       run: yarn test:integration
